spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: ripper
  default-assignee-name: ripper
  default-expiry-date: 2111-11-11